name: Preview Flask App via Ngrok

on:
  push:
    branches:
      - main  # Remplace par ta branche cible si besoin

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Python dependencies and Ngrok
      run: |
        pip install flask
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        sudo mv ngrok /usr/local/bin
        ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}

    - name: Start Flask App in background
      run: |
        nohup python3 __init__.py &
        sleep 5

    - name: Start Ngrok and show public URL
      run: |
        nohup ngrok http 5000 > /dev/null &
        sleep 10
        echo "Lien public accessible temporairement (120s) :"
        curl -s http://localhost:4040/api/tunnels | grep -o 'https://[a-z0-9]*\.ngrok\.io'

    - name: Attente de 120 secondes
      run: sleep 120
